import React from 'react'
import { useParams } from 'react-router-dom'


// Images Gallery
import imgGallery1 from './assets/gallery/actus-jv_gallery_0001.jpg'
import imgGallery2 from './assets/gallery/actus-jv_gallery_0002.jpg'
import imgGallery3 from './assets/gallery/actus-jv_gallery_0003.jpg'

// images body
import imgBody1 from './assets/body/actus-jv_img_0001.jpg'
import imgBody2 from './assets/body/actus-jv_img_0002.jpg'
import imgBody3 from './assets/body/actus-jv_img_0003.jpg'

// images carousel
import imgCarousel1 from './assets/carousel/jeuxvideo_img_carousel_0001.jpg'
import imgCarousel2 from './assets/carousel/jeuxvideo_img_carousel_0002.jpg'
import imgCarousel3 from './assets/carousel/jeuxvideo_img_carousel_0003.jpg'

import {
  Chapo,
  SectionTitle,
  Section,
  SectionImage,
  Img,
  ImgLegend
} from 'components/PieceOfWork/Gallery/shared'

import LANG from 'common/wording/lang'
import { Paragraph1 } from 'components/Paragraphs'
import GIFVideo from 'components/PieceOfWork/GIFVideo'

const CiteSciencesJeuVideo = () => {
  const { lang } = useParams()
  const isFr = lang === LANG.FR.SLUG
  return (
    <>
      <Section>
        <Chapo>
          {
            isFr
              ? 'Nous avons crÃ©Ã© un paysage vivant, gÃ©nÃ©rÃ© par les donnÃ©es, pour traduire l\'actualitÃ© dans l\'univers du jeu vidÃ©o. Cette installation crÃ©ative a Ã©tÃ© projetÃ©e pendant huit mois Ã  la CitÃ© des Sciences de Paris,  Ã  lâ€™occasion de sa grande exposition Jeu VidÃ©o.'
              : 'We created a living landscapeâ€”generated by dataâ€”to communicate and share news and events from the video games world. This creative installation was screened for 8 months at the CitÃ© des Sciences in Paris during a major video games exhibition.'
          }
        </Chapo>
      </Section>
      <Section>
        <SectionTitle>
          FormattedMessage: project-body-problem
        </SectionTitle>
        <Paragraph1>
          {
            isFr
              ? 'L\'actualitÃ© des jeux vidÃ©os est foisonnante, fruit de multiples sources d\'informations aux temporalitÃ©s diffÃ©rentes. La CitÃ© des Sciences voulait incarner cette vitalitÃ© et cette diversitÃ© par une installation visuelle poÃ©tique, au cÅ“ur de son exposition consacrÃ©e aux jeux vidÃ©os. Une difficultÃ© supplÃ©mentaire nous a Ã©tÃ© imposÃ©e\u00A0: l\'installation devait fonctionner en autonomie pendant les huit\u00A0mois Ã  la CitÃ© des Sciences de Paris.'
              : 'News about video games is everywhereâ€”there are many different and constant sources of information. The CitÃ© des Sciences wanted to capture this vitality and diversity by putting a poetic visual installation at the heart of its video games exhibition. An additional difficulty was imposed on us: the installation had to operate throughout the 8\u00A0months of the exhibition without any ongoing maintenance.'
          }
        </Paragraph1>
      </Section>
      <Section>
        <SectionImage>
          <Img src={imgBody1} />
        </SectionImage>
        <Section>
          <ImgLegend>
            {
              isFr
                ? 'Chaque sujet d\'actualitÃ© est reprÃ©sentÃ© par une planÃ¨te. La taille des noyaux est proportionnelle au nombre dâ€™articles qui le composent et le halo est  proportionnel au nombre de partages sociaux.'
                : 'A planet represents each news subject. The size of the nuclei is proportional to the number of articles on the subject and the halo is proportional to the number of social shares.'
            }
          </ImgLegend>
        </Section>
      </Section>
      <Section>
        <SectionTitle>
          FormattedMessage: project-body-data
        </SectionTitle>
        <Paragraph1>
          {
            isFr
              ? 'Notre matiÃ¨re premiÃ¨re Ã©tait faite de flux dâ€™articles issus dâ€™une trentaine de sources\u00A0: blogs spÃ©cialisÃ©s, sites dâ€™info gÃ©nÃ©ralistes, Google News, Yahoo News, etc. Ces bribes dâ€™actualitÃ© disparates Ã©taient re-traitÃ©es par notre partenaire Antidot pour obtenir une liste de thÃ¨mes hiÃ©rarchisÃ©s (clustering) via des algorithmes dâ€™apprentissage automatique.  Au cours des huit mois de l\'exposition, l\'application a traitÃ© plus de 20\u00A0000 articles et identifiÃ© environ 1\u00A0000 sujets dâ€™actualitÃ©.'
              : 'Our raw material was made up of streams of articles from around 30 sources, such as specialized blogs, general information sites, Google News, Yahoo News, etc. These disparate snippets of news were re-processed by our partner Antidot to obtain a list of hierarchical themes (clustering) via machine learning algorithms. During the 8 months of the exhibition, the application processed more than 20,000 articles and identified around 1,000 current topics.'
          }
        </Paragraph1>
      </Section>
      <Section>
        <SectionImage>
          <Img src={imgBody3} />
        </SectionImage>
        <Section>
          <ImgLegend>
            {
              isFr
                ? 'Nous avons Ã©tÃ© inspirÃ©s par le concept Â«\u00A0dâ€™informatique ambiante\u00A0Â», cette informatique diffuse et omniprÃ©sente, traduction d\'un monde oÃ¹ tous les systÃ¨mes informatiques seraient aussi libres et naturels que lâ€™air que nous respirons.'
                : 'We were inspired by the concept of â€˜ambient computingâ€™â€”an ubiquitous world where all computer systems would be as free and natural as the air we breathe.'
            }
          </ImgLegend>
        </Section>
      </Section>
      <Section>
        <SectionTitle>
          FormattedMessage: project-body-method
        </SectionTitle>
        <Paragraph1>
          {
            isFr
              ? 'Nous avons cherchÃ© Ã  construire une installation â€œcalmeâ€\u00A0: un dispositif qui se fond harmonieusement dans le paysage de l\'exposition, qui reste discret, Ã©lÃ©gant, reposant, qui ne saute pas aux yeux des visiteurs, et ne rÃ©clame pas d\'Ãªtre au centre de l\'attention. Nous voulions que les visiteurs s\'imprÃ¨gnent des information en passant, au milieu du brouhaha des autres installations interactives de l\'exposition. '
              : 'We sought to build a â€˜calmâ€™ installation. We wanted a device that blended harmoniously into the landscape of the exhibition, remaining discreet, elegant, relaxing; an installation that did not claim to be the center of attention. We wanted visitors to soak up the information in passing, amid the hubbub of the other interactive installations at the exhibition.'
          }
        </Paragraph1>
      </Section>
      <Section>
        <GIFVideo uri='429910647' formatPercent={37.5} />
        <ImgLegend>
          {
            isFr
              ? 'Lâ€™application est vivante, animÃ©e dâ€™une mystÃ©rieuse Ã©nergie insufflÃ©e par les donnÃ©es.'
              : 'The app comes alive thanks to a mysterious energy injected by the data.'
          }
        </ImgLegend>
      </Section>
      <Section>
        <SectionTitle>
          FormattedMessage: project-body-solution
        </SectionTitle>
        <Paragraph1>
          {
            isFr
              ? 'Nous avons traduit les articles sur les jeux vidÃ©os et leurs partages en un paysage onirique oÃ¹ chaque actualitÃ© est reprÃ©sentÃ©e par une planÃ¨te, ses partages par une aura lumineuse, et les derniers articles parus par des satellites. Lâ€™interface permet de comprendre quels sont les grands sujets dâ€™actualitÃ©, et quelle est leur importance. Elle montre les dÃ©calages entre des sujets trÃ¨s viraux, qui gÃ©nÃ¨rent beaucoup dâ€™articles, et les sujets de fond, qui sâ€™Ã©tirent de jour en jour.'
              : 'We transformed the articles on video games into a dreamlike landscape where each news item is represented by a planet, while its sharing is presented by a luminous aura; the most recently published articles are represented by satellites. The interface communicates the main news topics. It highlights the differences between very viral subjects that generate a lot of articles, and the more substantive subjects that are followed day after day.'
          }
        </Paragraph1>
      </Section>
      <Section>
        <SectionImage>
          <Img src={imgBody2} />
        </SectionImage>
      </Section>
      <Section>
        <SectionTitle>
          FormattedMessage: project-body-main-point
        </SectionTitle>
        <Paragraph1>
          {
            isFr
              ? 'Avec ce projet, nous avons poussÃ© le plus loin possible l\'idÃ©e de transformer les donnÃ©es en matiÃ¨re. Nous avons souvent recours aux mÃ©taphores du monde physique pour donner aux utilisateurs l\'impression que les donnÃ©es sont des choses concrÃ¨tes, apprÃ©hendables. Ici, nous nous Ã©tÃ© jusquâ€™Ã  crÃ©er un petit univers parallÃ¨le\u00A0: les objets de lâ€™application se partagent lâ€™espace disponible Ã  lâ€™intÃ©rieur de lâ€™Ã©cran, ils sâ€™attirent ou se repoussent, selon des lois physiques comme la gravitÃ©. GrÃ¢ce Ã  ces rÃ¨gles, l\'installation a pu Ã©voluer de faÃ§on autonome, au grÃ© des donnÃ©es reÃ§ues, pendant les huit mois de l\'exposition.'
              : 'With this project, we pursued the idea of transforming data into matter. We often use metaphors from the physical world to give users the impression that data represents concrete, tangible things. Here, we went as far as creating a small parallel universe: the objects of the app share the space inside the screen, they attract or repel each other in line with physical laws such as gravity. By following these rules, the installation was able to evolve independentlyâ€”based on the data receivedâ€”throughout the 8 months of the exhibition.'
          }
        </Paragraph1>
      </Section>
    </>
  )
}

const infosCiteSciencesJeuVideo = {
  component: CiteSciencesJeuVideo,
  client: {
    fr: 'CitÃ© des sciences et de l\'industrie de Paris',
    en: 'CitÃ© des sciences et de l\'industrie de Paris'
  },
  label: {
    fr: 'L\'actualitÃ© du jeu vidÃ©o',
    en: 'Video game news'
  },
  theme: {
    isDark: true,
    background: '#181E2C'
  },
  video: '427805729',
  results: {
    fr: 'ProjetÃ© sur grand Ã©cran en continu pendant 8 mois Ã  la CitÃ© des Sciences de Paris.',
    en: 'Projected on a big screen continuously for 8 months at Paris CitÃ© des Sciences.'
  },
  chapo: {
    fr: 'Traduire de faÃ§on poÃ©tique l\'actualitÃ© du jeu vidÃ©o.',
    en: 'Provide a poetic interpretation of video games news.'
  },
  caseStudy: {
    en: {
      label: 'A living landscape to translate current news related to video games',
      url: 'https://stories.dataveyes.com/a-living-landscape-to-translate-current-news-related-to-video-games-36c78c1d638f'
    },
    fr: {
      label: 'Un paysage vivant pour traduire lâ€™actualitÃ© dans lâ€™univers du jeu vidÃ©o',
      url: 'https://medium.com/dataveyes-stories-vf/un-paysage-vivant-pour-traduire-lactualit%C3%A9-dans-l-univers-du-jeu-vid%C3%A9o-3c62d6352595'
    }
  },
  category: {
    fr: 'Installation crÃ©ative',
    en: 'Creative installation'
  },
  date: {
    fr: '2013 - 4 mois',
    en: '2013 - 4 months'
  },
  carousel: {
    isBig: false,
    pics: [imgCarousel1, imgCarousel2, imgCarousel3]
  },
  slug: 'cite-des-sciences-jeu-video',
  isOnHome: false,
  serviceId: 'prototyping',
  galleryPics: [
    {
      src: imgGallery1
    },
    {
      src: imgGallery2
    },
    {
      src: imgGallery3
    }
  ]
}

export default CiteSciencesJeuVideo
export { infosCiteSciencesJeuVideo }
