mv projects/transcinema.md _unused/transcinema.md~  
mv projects/0-selectprojects.md _unused/0-selectprojects.md~
mv projects/3feet-openwave.md _unused/3feet-openwave.md~
mv projects/3feetofftheground.md _unused/3feetofftheground.md~
mv projects/11inc-thedoctorscompany.md _unused/11inc-thedoctorscompany.md~
mv projects/300feetout-shantimaurice.md _unused/300feetout-shantimaurice.md~
mv projects/allergybookcompany.md _unused/allergybookcompany.md~
mv projects/audiofeast.md _unused/audiofeast.md~
mv projects/blurb.md _unused/blurb.md~
mv projects/chronopolis.md _unused/chronopolis.md~
mv projects/cks-apple-quicktime.md _unused/cks-apple-quicktime.md~
mv projects/cks-appledesignportfolio.md _unused/cks-appledesignportfolio.md~
mv projects/cks-levis.md _unused/cks-levis.md~
mv projects/cks-mattel.md _unused/cks-mattel.md~
mv projects/cks-nikealphaproject.md _unused/cks-nikealphaproject.md~
mv projects/cks-quicktime.md _unused/cks-quicktime.md~
mv projects/cks-visa-rugby.md _unused/cks-visa-rugby.md~
mv projects/compass-lumenetix.md _unused/compass-lumenetix.md~
mv projects/california-college-of-the-arts.md _unused/california-college-of-the-arts.md~
mv projects/creativefocus.md _unused/creativefocus.md~
mv projects/dr-tingleton.md _unused/dr-tingleton.md~
mv projects/drdc-luminoxwatch.md _unused/drdc-luminoxwatch.md~
mv projects/dynamic-emc-splatter.md _unused/dynamic-emc-splatter.md~
mv projects/elixir-opesadvisors.md _unused/elixir-opesadvisors.md~
mv projects/fine-design-stagsleapwinery.md _unused/fine-design-stagsleapwinery.md~
mv projects/flax-media-pbs.md _unused/flax-media-pbs.md~
mv projects/fuseproject-briggo.md _unused/fuseproject-briggo.md~
mv projects/gilmourcraves.md _unused/gilmourcraves.md~
mv projects/gmotionstudios.md _unused/gmotionstudios.md~
mv projects/capacitor.md _unused/capacitor.md~
mv projects/gregory-cowleystudios.md _unused/gregory-cowleystudios.md~
mv projects/hong-kong.md _unused/hong-kong.md~
mv projects/ideo-chaseconcepts.md _unused/ideo-chaseconcepts.md~
mv projects/ideo-hp-timeline.md _unused/ideo-hp-timeline.md~
mv projects/ideo-intel-zephyros.md _unused/ideo-intel-zephyros.md~
mv projects/ideo-thoughtless-acts.md _unused/ideo-thoughtless-acts.md~
mv projects/intuit.md _unused/intuit.md~
mv projects/juicystock.md _unused/juicystock.md~
mv projects/lunafest.md _unused/lunafest.md~
mv projects/mad-ibm-db2.md _unused/mad-ibm-db2.md~
mv projects/cncmachine.md _unused/cncmachine.md~
mv projects/motorola-chameleon.md _unused/motorola-chameleon.md~
mv projects/odopod-hpadbanners.md _unused/odopod-hpadbanners.md~
mv projects/odopod-intelpentium3.md _unused/odopod-intelpentium3.md~
mv projects/oreilly-safariu.md _unused/oreilly-safariu.md~
mv projects/photo-adobe.md _unused/photo-adobe.md~
mv projects/photo-architect-magazine.md _unused/photo-architect-magazine.md~
mv projects/photo-kenwood.md _unused/photo-kenwood.md~
mv projects/photo-michael-chiarello.md _unused/photo-michael-chiarello.md~
mv projects/photo-ogilvy-one.md _unused/photo-ogilvy-one.md~
mv projects/photo-overland-equipment.md _unused/photo-overland-equipment.md~
mv projects/countless.md _unused/countless.md~
mv projects/photo-selectquote.md _unused/photo-selectquote.md~
mv projects/photo-sequoia.md _unused/photo-sequoia.md~
mv projects/photo-sfmoma.md _unused/photo-sfmoma.md~
mv projects/photo-skanska.md _unused/photo-skanska.md~
mv projects/photo-smartrise.md _unused/photo-smartrise.md~
mv projects/photo-snibbe-interactive.md _unused/photo-snibbe-interactive.md~
mv projects/photo-stochasticlabs.md _unused/photo-stochasticlabs.md~
mv projects/photo-superlawyers.md _unused/photo-superlawyers.md~
mv projects/photo-the-sak.md _unused/photo-the-sak.md~
mv projects/photo-university-games.md _unused/photo-university-games.md~
mv projects/mpps.md _unused/mpps.md~
mv projects/photo-usa-today.md _unused/photo-usa-today.md~
mv projects/punchcut-cingulardeveloperstool.md _unused/punchcut-cingulardeveloperstool.md~
mv projects/punchcut-dwellvisualizer.md _unused/punchcut-dwellvisualizer.md~
mv projects/raspberry-pis.md _unused/raspberry-pis.md~
mv projects/razorfish-hondausa.md _unused/razorfish-hondausa.md~
mv projects/razorfish-microsoftfrontpage.md _unused/razorfish-microsoftfrontpage.md~
mv projects/ricoh-labs-logo.md _unused/ricoh-labs-logo.md~
mv projects/simplestar.md _unused/simplestar.md~
mv projects/teak-wantedsanta.md _unused/teak-wantedsanta.md~
mv projects/voicebox.md _unused/voicebox.md~
mv projects/rx-gallery.md _unused/rx-gallery.md~
mv projects/wolfolins-fineartmuseums.md _unused/wolfolins-fineartmuseums.md~
mv projects/thetestproject.md _unused/thetestproject.md~
mvprojects/three-minute-picture-show.md _unused/three-minute-picture-show.md~